export const CODEGEN_MESSAGE = `
/*
    * This file was automatically generated by thebigsasha's Sanity Codegen. (http://thebigsasha.github.io/sanity_config_creator/)
    * Look for todos in the code for places where codegen was unable to generate code due to lack of context.
    * 
    * Generated on: ${new Date().toLocaleString()} (local time)
    *
    * Some assembly required:
    * - in \`sanity.config.ts\`, add the following to the \`schema.types\` array:
    *   the type interfaces generated for all of the schemas in this codegen.
    * - (optional) for canonical code organization, move code:
    *   - type interfaces to \`types/index.ts\`
    *   - queries to \`lib/sanity.queries.ts\`
    *   - object definitions to their own files in \`schemas/objects\`
    *   - document definitions to their own files in \`schemas/documents\`
    *   - singleton definitions to their own files in \`schemas/singletons\`
    *
    * Please report any issues to GitHub: https://github.com/TheBigSasha/sanity_config_creator/issues
    *
    * Thanks for using my lil' app!
*/
`;

export const MINI_CODEGEN_MESSAGE = `
/*
    * This file was automatically generated by thebigsasha's Sanity Codegen. (http://thebigsasha.github.io/sanity_config_creator/)
    * Read more at the link above.
*/
`;
